### ISSUE TITLE
Uncaught TypeError: app.provide is not a function

### ISSUE THREAD

**Issue by dejardine** [ubclaunchpad/vue-fathom#1]
Getting the following error when trying to implement this in Nuxt, any ideas?

Uncaught TypeError: app.provide is not a function
    at Object.install (vue-fathom.esm.js?04e3:33:1)
    at Function.Vue.use (vue.runtime.esm.js?2b0e:5121:1)
    at eval (fathom.client.js?5ad2:4:1)
    at Module../plugins/fathom.client.js (app.js:3730:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (index.js:55:92)
    at Module../.nuxt/index.js (app.js:215:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)

**Comment by mahammad-sixberries** [comment]
"@ubclaunchpad/vue-fathom": "1.0.7",

import * as VueFathom from '@ubclaunchpad/vue-fathom';
